# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    'env(JWT_VALIDITY)': 300

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    App\Api\Swagger\ApiDocGenerator:
        arguments:
            - '@nelmio_api_doc.generator_locator'

    Nelmio\ApiDocBundle\ModelDescriber\ObjectModelDescriber:
        alias: 'nelmio_api_doc.model_describers.object'
        public: true

    Symfony\Component\Serializer\Serializer:
        alias: Symfony\Component\Serializer\SerializerInterface

    App\Security\TokenAuthenticator:
        arguments:
            $secret: '%env(JWT_SECRET_KEY)%'

    App\Security\TokenGenerator:
        arguments:
            $validFor: '%env(int:JWT_VALIDITY)%'
            $secret: '%env(JWT_SECRET_KEY)%'